# Changes here will be overwritten by Copier
_commit: fdc7a96
_src_path: gh:34j/pypackage-template-fork
add_me_as_contributor: false
copyright_year: '2023'
documentation: true
email: 34j.95a2p@simplelogin.com
full_name: 34j
github_username: 34j
initial_commit: false
open_source_license: MIT
open_with_vscode: false
package_name: mecab_text_cleaner
project_name: MeCab Text Cleaner
project_short_description: Simple Python package for getting japanese reading (yomigana)
    using MeCab
project_slug: mecab-text-cleaner
run_poetry_install: false
setup_github: false
setup_pre_commit: false
setup_venv: false
venv_version: '3.10'

